from typing import Protocol, runtime_checkable

from textual.widget import Widget


@runtime_checkable
class BlockProtocol(Protocol):
    def block_cursor_up(self) -> Widget | None: ...
    def block_cursor_down(self) -> Widget | None: ...
    def get_cursor_block(self) -> Widget | None: ...
    def block_cursor_clear(self) -> None: ...
